//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopSafe_Web.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopSafeEntities : DbContext
    {
        public ShopSafeEntities()
            : base("name=ShopSafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capacity> Capacities { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Store_Location> Store_Location { get; set; }
    }
}
